training:
  data:
    sources:
      - s3://{}/reviews/reviews_partition_1.csv
    frac: null
    n: 30000
  model_meta:
    path: models/{}.pickle
    name: logreg_on_tfidf
    desc: Logistic Regression model trained on TF-IDF features of preprocessed text
    version: 1
  preprocessor:
    use_flg: True
    module: sentiment_analysis.core.preprocessing
    class: TextPreprocessor
    hyperparams:
      use_lemmatizer: True
      use_lowercase: True
      remove_stopwords: True
  vectorizer:
    use_flg: True
    module: sklearn.feature_extraction.text
    class: TfidfVectorizer
    hyperparams:
      ngram_range: [1, 2]
      max_features: 7500
      sublinear_tf: True       
  classifier:
    use_flg: True
    module: sklearn.linear_model
    class: LogisticRegression
    hyperparams:
      max_iter: 1000
crawler: null
app:
  name: 'MyApp'
  model_path: models/{}.pickle
  model_name: logreg_on_tfidf
  model_version: 1
